### ISSUE TITLE
new R package checklist

### ISSUE THREAD

**Issue by russHyde** [russHyde/russ-hyde#6]
While creating new package `homologiser` and `reeq`, what steps were required

[Added to blog on 2019-08-23]

**Comment by russHyde** [comment]
`.lintr` file
[Moved to blog]

**Comment by russHyde** [comment]
`.travis.yml` file

[Moved to blog]

**Comment by russHyde** [comment]
? Other things:

- lifecycle badge (`use_lifecycle_badge("experimental")`)
- R-version regression tests (`use_tidy_ci()`; make sure to store your .travis.yml since it will be overwritten)
- Code of conduct (`use_code_of_conduct()` or `use_tidy_coc()`)

**Comment by russHyde** [comment]
## Source Code

_TODO_ [Add to blog]

- [ ] - `usethis::use_package`
- [ ] - Adding code:
    - [ ] - add a test
    - [ ] - BUILD && TEST && watch it fail
    - [ ] - add some source code to get the test to pass
    - [ ] - BUILD && TEST
    - [ ] - clean up your test and your code
- [ ] - Document all exported functions
    - `@export` a function
    - BUILD && TEST && CHECK
    - Fix all issues that are raised during `R CMD check` run
        - eg, fill in all `@importFrom`, `@param` fields
- [ ] - Style and lint all code
- [ ] - Check coverage of the code
- [ ] - Use goodpractice to run various code-quality heuristics
- [ ] - Usability documentation (Vignettes, READMEs)

----

- Added a source file (`homologue_functions.R`) to `R/`
    - The presence of this file means `goodpractice` can now run (it throws warnings if there's no source files in a package)
- `goodpractice::gp(checks = all_checks()[-2])` was ran: this disregards the `cyclocomp` check which causes problems in the conda environments I use but runs all other checks
    - No issues are flagged at this stage
- Tests
    - Add a failing test and watch it all _burn to the ground_
- Tests for first function were added
    - Checked that tests failed using Ctrl-Shift-T
- First function written into source code (copied from an existing project)
    - it depended upon another one of my functions (stated using an @include in the roxygen docs)
    - building failed because the `@include`d file was missing; commented out the `@include` but wouldn't build/document since by this point the `@include`d file had been added to DESCRIPTION::Collate; deleted the included file from DESCRIPTION::Collate and rebuilt
    - build now passed; check failed - some package dependencies had not been added
- Package dependencies of the new functions were added
    - devtools::use_package("dplyr") # etc
    - Build again
    - Check again - failed because the `@include` dependants haven't been copied in
- Added a second source-file and test-file
    - because a collate field already existed in DESCRIPTION, this new file wasn't added directly to the collate section (????)
    - deleted the collate section from DESCRIPTION
    - Build
    - Added the `@include` argument back into the earlier source file
    - Build
    - Check failed because further code had to be copied over into the second file
    - Copied over the tests/code for the other functions
    - Build / Test / Check / goodpractice() / style_pkg() / lint_package()
        - renamed vars etc until all steps of the above passed
